// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[EOF-1]
	_ = x[LEFT_PAREN-2]
	_ = x[RIGHT_PAREN-3]
	_ = x[LEFT_BRACE-4]
	_ = x[RIGHT_BRACE-5]
	_ = x[COMMA-6]
	_ = x[DOT-7]
	_ = x[MINUS-8]
	_ = x[PLUS-9]
	_ = x[SEMICOLON-10]
	_ = x[STAR-11]
	_ = x[SLASH-12]
	_ = x[LESS-13]
	_ = x[LESS_EQUAL-14]
	_ = x[GREATER-15]
	_ = x[GREATER_EQUAL-16]
	_ = x[EQUAL-17]
	_ = x[EQUAL_EQUAL-18]
	_ = x[BANG-19]
	_ = x[BANG_EQUAL-20]
	_ = x[STRING-21]
	_ = x[NUMBER-22]
	_ = x[IDENTIFIER-23]
}

const _TokenType_name = "INVALIDEOFLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSEMICOLONSTARSLASHLESSLESS_EQUALGREATERGREATER_EQUALEQUALEQUAL_EQUALBANGBANG_EQUALSTRINGNUMBERIDENTIFIER"

var _TokenType_index = [...]uint8{0, 7, 10, 20, 31, 41, 52, 57, 60, 65, 69, 78, 82, 87, 91, 101, 108, 121, 126, 137, 141, 151, 157, 163, 173}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
